### PR TITLE
Added setting of cartesian speed and acceleration 

### PR DESCRIPTION
**Pull request by Zarnack**
# Description
This PR fixes the issue #45 by changing the max_cartesian_speed setter to set the max_velocity_scaling_factor of the cartesian_path_request.
This PR also adds a max_cartesian_acceleration setter and getter to set the max_acceleration_scaling_factor of the cartesian_path_request.

# Testing
Tested with a real and simulated franka panda robot via the move_to_pose command with the cartesian flag set to true.
I used the BiTRRT algorithm from the OMPL and the PTP algorithm from the PILZ trajectory generator.

### CODE REVIEW

**Comment by amalnanavati** [comment]
The pattern used for all other cartesian path parameters is that the property setters/getters set them in `self.__move_action_goal.request` and then the `_plan_cartesian_path` function copies them into `self.__cartesian_path_request`. See [here](https://github.com/AndrejOrsula/pymoveit2/blob/bcd2aa91e04adaf6adb885a460216d483b5c212f/pymoveit2/moveit2.py#L1740) for multiple such examples. 

Thus, I'd recommend reverting back to the original property setters/getters, and instead copying those values from `self.__move_action_goal.request` to `self.__cartesian_path_request` in `_plan_cartesian_path`. That way, we continue to maintain the same functionality regardless of whether one is using the MoveGroup action or just calling the planning service in isolation.

**Comment by Zarnack** [comment]
I do agree, but to avoid any further confusion the setter and getter for _max_cartesian_speed_ should be removed and the corresponding value in the MotionPlanRequest be set to a default value (0.0) as it is currently not used within moveit2.

--> According to the message description of [MotionPlanRequest.msg](https://github.com/ros-planning/moveit_msgs/blob/humble/msg/MotionPlanRequest.msg) the parameter _cartesian_speed_limited_link_ and _max_cartesian_speed_ requires the _default_planner_request_adapters/SetMaxCartesianEndEffectorSpeed_ which only exists for moveit1.

**Comment by amalnanavati** [comment]
Removing the setter/getter of those properties, as they are not yet used in MoveIt2, seems reasonable to me.

(Although to be clear, I am just a contributor to this library, not an author/maintainer, so I'd recommend waiting for @AndrejOrsula to weigh in before making that change, since that would be a breaking change.)

**Comment by Zarnack** [comment]
Done and tested in simulation.

**Review by AndrejOrsula — APPROVED** [review]
Thanks a lot!

**Pull request merged**
