### PR TITLE
Add support for KUKA LBRs

### PR DESCRIPTION
**Pull request by mhubii**
Hi @AndrejOrsula and thank you for this great work!

We recently found that users requested help with moveit and I think your repository simplifies interfacing it greatly.

This pull request aims to add support for KUKA LBRs (iiwa7, iiwa14, med7, med14) in https://github.com/lbr-stack/lbr_fri_ros2_stack.

In the `lbr_fri_ros2_stack` everything is namespaced by robot name, that includes for example `/move_action` action server.

- [ ] Namespace support in `pymoveit2` ?
- [ ] Updates in `lbr_fri_ros2_stack` to allow `execute_via_moveit=False`, see https://github.com/AndrejOrsula/pymoveit2/blob/5b35728306665e7f21fe2ab1ee5bb42565c68e12/pymoveit2/moveit2.py#L51

Could you please help us integrate?

Or would you rather recommend to use the moveit python bindings?

Thank you for the help!

### CODE REVIEW

**Comment by mhubii** [comment]
Refers to https://github.com/lbr-stack/lbr_fri_ros2_stack/issues/133

**Comment by AndrejOrsula** [comment]
Hello @mhubii,

Thank you for your contribution!


> - [ ] Namespace support in `pymoveit2` ?

I am not certain. I was under the assumption that specifying `namespace` for your [Node](https://docs.ros2.org/latest/api/rclpy/api/node.html) before instantiating [MoveIt2](https://github.com/AndrejOrsula/pymoveit2/blob/5b35728306665e7f21fe2ab1ee5bb42565c68e12/pymoveit2/moveit2.py#L38) class would automatically resolve the namespacing for you. However, I have not tested it so I am unsure.

> - [ ] Updates in `lbr_fri_ros2_stack` to allow `execute_via_moveit=False`, see https://github.com/AndrejOrsula/pymoveit2/blob/5b35728306665e7f21fe2ab1ee5bb42565c68e12/pymoveit2/moveit2.py#L51

I am sorry, but I am unsure what you mean. The `execute_via_moveit` parameter already defaults to `False` but you can change it during initialization.

> Could you please help us integrate?

Would you mind testing the `namespace` via Node mentioned above?

At the moment, I use the Python interface for MoveIt 2 only for a course that employs [`phantomx_pincher`](https://github.com/snt-spacer/phantomx_pincher) robots. This repository covers everything that the course requires, so I won't be working towards adding new features (e.g. automatic parsing of `robot_description` to make these PRs obsolete). I am happy to review/merge any PRs, though.

> Or would you rather recommend to use the moveit python bindings?

I have not tested `moveit2_py` extensively, so I cannot give you an answer. It is an official Python interface, so it might be a better option in the long term - hence, it has been mentioned at the top of the README of this repository since it was announced.

**Review by AndrejOrsula — APPROVED** [review]

**Comment by mhubii** [comment]
hi @AndrejOrsula and thanks for coming back so briefly. Sorry this PR wasn't ready for merge

**Comment by AndrejOrsula** [comment]
No worries. Feel free to open another PR if needed.

**Pull request merged**
